# Postgres db configuration
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/charitydb
    username: charity
    password: charity
  jpa:
    database_platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

      
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true